# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6fd0a0f45b77b31d2d2cd7d7db7746b7f3ee13587f4e336cd290e0f559424c8bedbf9f3baf95dfd11060814dba5e1467149aa42c07c8f969c98cb666298cdd5
  stripe_publishable_key: pk_test_wsRoH8oIsU9HHFY8sr6WAaAm
  stripe_secret_key: sk_test_RimLkMtxOkKneuZuyolRexlG

test:
  secret_key_base: bf446ce3cf252033345a2de5023b2ecc1064f101f87fe26e6a4453c8863d1e12a57fd8bda8d9ce3b9d49b0233107221d2c909211650b6f9f2061e2fe9e24942a
  stripe_publishable_key: pk_test_wsRoH8oIsU9HHFY8sr6WAaAm
  stripe_secret_key: sk_test_RimLkMtxOkKneuZuyolRexlG

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']
